# GitHub workflow for deploying the Docker image to Docker Hub
# by retagging concept:test-build to concept:latest.
name: deploy_docker

on:
    push:
        branches:
          - master

jobs:
    deploy_docker:
        runs-on: ubuntu-20.04
        steps:
          - name: 🚀 Deploy Docker image
            env:
                docker_username: ${{ secrets.DOCKER_USERNAME }}
            if: env.docker_username
            run: |
                docker pull ${{ secrets.DOCKER_USERNAME }}/concept:test-build
                docker pull ${{ secrets.DOCKER_USERNAME }}/concept:latest
                if [ \
                    "$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/concept:test-build)" \
                    == \
                    "$(docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/concept:latest)" \
                ]; then
                    echo "No change to Docker image"
                    exit 0
                fi
                docker tag \
                    ${{ secrets.DOCKER_USERNAME }}/concept:test-build \
                    ${{ secrets.DOCKER_USERNAME }}/concept:latest
                docker login \
                    -u ${{ secrets.DOCKER_USERNAME }} \
                    -p ${{ secrets.DOCKER_PASSWORD }} \
                    2>/dev/null
                docker push ${{ secrets.DOCKER_USERNAME }}/concept:latest
                docker logout

