# GitHub workflow for testing the building of the docs
name: test_docs

on:
    pull_request:
        branches:
          - master
        paths:
          - 'concept/docs/**'

jobs:
    test_docs:
        runs-on: [self-hosted, linux]
        steps:
          - name: 🛎 Checkout
            uses: actions/checkout@v2
          - name: 📝 Set Docker username
            env:
                docker_username: ${{ secrets.DOCKER_USERNAME }}
            run: |
                [ -n "${docker_username}" ] || docker_username=jmddk
                echo "docker_username=${docker_username}" >> "${GITHUB_ENV}"
          - name: 🐋 Pull Docker image
            run: docker pull ${docker_username}/concept:latest
          - name: 📖 Build docs
            run: |
                docker run \
                    -v "${GITHUB_WORKSPACE}":/github \
                    --rm \
                    ${docker_username}/concept:latest \
                    bash -c ': \
                        && cd / \
                        && source ~/.bashrc \
                        && rm -rf "${concept_dir}" \
                        && cp -r /github/concept "${concept_dir}" \
                        && (cd "${concept_dir}" && make docs) \
                    '

